### PR TITLE
Feat: reset authorization header in http requests in NGSIToCKAN processor

### PR DESCRIPTION
**Pull request by ranim-n**

### CODE REVIEW

**Comment by bobeal** [comment]
@ranim-n your PR is empty

**Comment by ranim-n** [comment]
> @ranim-n your PR is empty

I think when choosing `Show all changes` The PR appears empty because I undid the changes I did before. If you see changes from one commit they are there

**Comment by bobeal** [comment]
> > @ranim-n your PR is empty
> 
> I think when choosing `Show all changes` The PR appears empty because I undid the changes I did before. If you see changes from one commit they are there

you should have created a new branch on top of the 1.27, not a new branch on top of the merged branch

**Comment by bobeal** [comment]
so I merged it to see what happened and ...

**Pull request merged**
